/* tslint:disable */
/* eslint-disable */
/**
 * OnlineStore.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrderItemResponse
 */
export interface OrderItemResponse {
    /**
     * 
     * @type {string}
     * @memberof OrderItemResponse
     */
    productId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemResponse
     */
    price?: number;
}
