/* tslint:disable */
/* eslint-disable */
/**
 * OnlineStore.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    productName?: string ;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    categoryId?: string;
}
